---
# tasks file for ansible-role-sshcopy
- name: Ensure .ssh directory exists, if not create it.
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: '0700'

- name: Ensure authorized_keys file exists, if not create it.
  ansible.builtin.file:
    path: ~/.ssh/authorized_keys
    state: touch
    mode: '0700'

- name: Copying ssh keys
  ansible.builtin.lineinfile:
    path: ~/.ssh/authorized_keys
    state: present
    line: "{{ item }}"
  loop: "{{ keys }}"
